name: MD5 Circle CI

on:
  push:
    branches:
      - main

  workflow_dispatch:
      
  schedule:
  - cron: "10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name ${{ secrets.NAME }}

      - name: Generate MD5 Hash
        run: |
          echo "Generating new keys..."
          bash generate.sh 32 > new_key_list

      - name: Generate Message & Commit
        run: |
          git add -A
          
          arr[0]="chore(bot): 😂 Generated keys"
          arr[1]="chore(bot): 😱 Generated keys"
          arr[2]="chore(bot): 👿 Generated keys"
          arr[3]="chore(bot): 💩 Generated keys"
          arr[4]="chore(bot): 🙏 Generated keys"
          arr[5]="chore(bot): 🙈 Generated keys"
          arr[6]="chore(bot): 🐐 Generated keys"
          arr[7]="chore(bot): 🤖 Generated keys"
          arr[8]="chore(bot): 🟩 Generated keys"
          arr[9]="chore(bot): 👻 Generated keys"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -am "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.PAT_GITHUB_TOKEN }}
